### ISSUE TITLE
Could not find artifact org.codehaus.mojo:sql-maven-plugin:jar:3.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by grugna** [mojohaus/sql-maven-plugin#24]
When I run mvn test I get this error: "[ERROR] Failed to execute goal on project maven-sql-plugin: Could not resolve dependencies for project com.hmkcode:maven-sql-plugin:jar:1.0-SNAPSHOT: Could not find artifact org.codehaus.mojo:sql-maven-plugin:jar:3.0.0-SNAPSHOT -> [Help 1]"

you can see my pom.xml file here:

`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

        <modelVersion>4.0.0</modelVersion>

        <groupId>com.hmkcode</groupId>
        <artifactId>maven-sql-plugin</artifactId>
        <version>1.0-SNAPSHOT</version>
        <packaging>jar</packaging>

        <name>maven-sql-plugin</name>
        <url>http://maven.apache.org</url>

        <properties>
                <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
                <maven.compiler.source>1.6</maven.compiler.source>
                <maven.compiler.target>1.6</maven.compiler.target>
        </properties>

        <dependencies>
                <dependency>
                        <groupId>junit</groupId>
                        <artifactId>junit</artifactId>
                        <version>4.11</version>
                        <scope>test</scope>
                </dependency>

                <dependency>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>sql-maven-plugin</artifactId>
                        <version>3.0.0-SNAPSHOT</version>
                        <type>maven-plugin</type>
                </dependency>
        </dependencies>

        <build>
                <plugins>
                        <plugin>
                                <groupId>org.codehaus.mojo</groupId>
                                <artifactId>sql-maven-plugin</artifactId>
                                <version>3.0.0-SNAPSHOT</version>

                                <dependencies>
                                        <dependency>
                                                <groupId>mysql</groupId>
                                                <artifactId>mysql-connector-java</artifactId>
                                                <version>5.1.9</version>
                                        </dependency>
                                </dependencies>

                                <configuration>
                                        <driver>com.mysql.jdbc.Driver</driver>
                                        <url>jdbc:mysql://localhost:3306/myDB</url>
                                        <username>root</username>
                                        <password></password>
                                </configuration>
                                <executions>
                                        <execution>
                                                <id>drop-table</id>
                                                <phase>process-test-resources</phase>
                                                <goals>
                                                        <goal>execute</goal>
                                                </goals>
                                                <configuration>
                                                        <autocommit>true</autocommit>
                                                        <sqlCommand>DROP TABLE IF EXISTS person</sqlCommand>
                                                </configuration>
                                        </execution>
                                </executions>
                        </plugin>
                </plugins>
        </build>
</project>`

**Comment by khmarbaise** [comment]
A plugin as a dependency in a build is simply wrong. Furthermore sql-maven-plugin exists currently only in version 1.5 so you will never find a version 3.0.0-... apart from that SNAPSHOT's are not deployed to central....

**Comment by grugna** [comment]
@khmarbaise  yes, sorry. I copied that by mistake, it was random stuff that I was trying  since I had that error. I will change it to version 1.5 then. Thank you!

**Comment by AKEIng** [comment]
may you show the correct configuration to work this out,thanks a lot
