### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Tastelezz** [mojohaus/sql-maven-plugin#8]
It would be nice to introduce another optional parameter which controls how to to behave in case of missing **srcFiles**. The use case I have in mind is the definition of the full list of all _SQL_ files to be executed in the proper order for the assembly module of a project. This configuration could be defined once in the _pluginManagement_ and reused by all modules the assembly is made of if the plugin would silently ignore missing _SQL_ files. This way we could avoid highly redundant configurations in all the modules.

**Comment by khmarbaise** [comment]
What about providing a patch ?
